export default [ // upsert contents to DB when this file gets big.
  {
    tabId: 1,
    name: 'Info',
    displayName: 'Room Information',
    iconColor: '#fffad5',
    bgColor: '#ffffff',
    icon: 'android-share-alt',
    description: 'Invite others to this room',
  },
  {
    tabId: 10,
    name: 'VideoChat',
    displayName: 'Video chat',
    iconColor: '#fffad5',
    bgColor: '#ffffff',
    icon: 'videocamera',
    description: 'Video chat',
  },
  // {
  //   tabId: 30,
  //   name: 'Settings',
  //   displayName: 'Settings',
  //   iconColor: '#acf0f2',
  //   ContentBgColor: '',
  //   bgColor: '',
  //   icon: 'ios-settings',
  //   description: 'Configure your webcam and Room settings',
  // },
  {
    tabId: 40,
    name: 'QuillPad',
    displayName: 'QuillPad',
    iconColor: '#fff0a5',
    bgColor: '#ffffff',
    icon: 'document-text',
    description: 'Shared Richtext document',
  },
  {
    tabId: 41,
    name: 'CodePad',
    displayName: 'CodePad',
    iconColor: 'turquoise',
    bgColor: '',
    icon: 'code-working',
    description: 'Shared Code editor',
  },
  {
    tabId: 31,
    name: 'Chat',
    displayName: 'Chat',
    iconColor: '#9ac16e',
    bgColor: '#faebd7',
    icon: 'chatbubbles',
    description: 'Chat messaging',
  },
  {
    tabId: 100,
    name: 'DiscoverTabs',
    displayName: 'Discover Tabs',
    iconColor: '#7dd3f5',
    bgColor: '#ffffff',
    icon: 'ios-plus',
    description: 'Discover more tabs',
  },
];
