export default [ // upsert contents to DB when this file gets big.
  {
    tabId: 1,
    name: 'Info',
    DisplayName: 'Room Information',
    iconColor: '#fffad5',
    bgColor: '#ffffff',
    icon: 'android-share-alt',
    description: 'Invite others to this room',
  },
  {
    tabId: 2,
    name: 'Settings',
    DisplayName: 'Settings',
    iconColor: '#acf0f2',
    ContentBgColor: '',
    bgColor: '',
    icon: 'ios-settings',
    description: 'Configure your webcam and Room settings',
  },
  {
    tabId: 3,
    name: 'QuillPad',
    DisplayName: 'QuillPad',
    iconColor: '#fff0a5',
    bgColor: '#ffffff',
    icon: 'document-text',
    description: 'Shared Richtext document',
  },
  {
    tabId: 4,
    name: 'CodePad',
    DisplayName: 'CodePad',
    iconColor: 'turquoise',
    bgColor: '',
    icon: 'code-working',
    description: 'Shared Code editor',
  },
  {
    tabId: 5,
    name: 'Chat',
    DisplayName: 'Chat',
    iconColor: '#9ac16e',
    bgColor: '#faebd7',
    icon: 'chatbubbles',
    description: 'Chat',
  },
  {
    tabId: 6,
    name: 'DiscoverTabs',
    DisplayName: 'Discover Tabs',
    iconColor: '#7dd3f5',
    bgColor: '#ffffff',
    icon: 'ios-plus',
    description: 'Discover more tabs',
  },
];
