// ME_FROM_THE_PAST: If the type of messages start to grow use nested messageSwitches
// to orgranise their handlers.
export default {
  SIGNAL: 'SIGNAL',
  ROOM_UPDATED: 'ROOM_UPDATED',
  TAB_READY: 'TAB_READY',
  TAB_MESSAGE: 'TAB_MESSAGE',
  MEDIA_STREAM: 'MEDIA_STREAM',
  SPEAKING: 'SPEAKING',
  SPEAKING_STOPPED: 'SPEAKING_STOPPED',
  STREAM_UPDATE_REQUEST: 'STREAM_UPDATE_REQUEST',
  STREAM_UPDATE: 'STREAM_UPDATE',
};

