export default {
  INITIALIZING: 'INITIALIZING',
  STOPPED: 'STOPPED',
  CONNECTED: 'CONNECTED',
  DISCONNECTED: 'DISCONNECTED',
  TRYING_TO_CONNECT: 'TRYING_TO_CONNECT',
  ERROR: 'ERROR',
  WARNING: 'WARNING',
};

