export default {
  DATA: {
    BROADCAST: 'DATA_BROADCAST',
    P2P: 'DATA_P2P',
  },
  MEDIA: {
    BROADCAST: 'MEDIA_BROADCAST',
    P2P: 'MEDIA_P2P',
  },
  PRIMARY_DATA_STREAM: 'PRIMARY_DATA_STREAM',
  PRIMARY_MEDIA_STREAM: 'PRIMARY_MEDIA_STREAM',
  MEDIA_STREAM: 'MEDIA_STREAM',
};

