const roomMessageTypes = {
  SPEECH: 'SPEECH',
  STREAM_SUBSCRIBE_SUCCESS: 'STREAM_SUBSCRIBE_SUCCESS',
  MUTE_VIDEO: 'MUTE_VIDEO',
  UNMUTE_VIDEO: 'UNMUTE_VIDEO',
  MUTE_AUDIO: 'MUTE_AUDIO',
  UNMUTE_AUDIO: 'UNMUTE_AUDIO',
};

export default roomMessageTypes;
